version: 2.1

jobs:
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - run:
          name: Change Permissions of deploy.sh
          command: ssh -oStrictHostKeyChecking=no -v $USER@$DNS "chmod +x ./deploy.sh"
      - run:
          name: Execute deploy.sh
          command: ssh -oStrictHostKeyChecking=no -v $USER@$DNS "./deploy.sh"

workflows:
  deploy-to-ec2:
    jobs:
      - deploy