# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-nodejs
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and
# run tests across different versions of node

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  server:
    name: Build and Test Server
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        mongodb-version: ["6.0", "7.0", "8.0"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache-dependency-path: server/package-lock.json
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install backend dependencies
      - name: Install Backend Dependencies
        run: |
          cd server
          npm ci

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      # Run backend tests
      - name: Run Backend Tests
        run: |
          cd server
          npm run test

  client:
    name: Build React Client
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: borgir-app/package-lock.json
          node-version: "20.x"
          cache: "npm"
      - name: Install dependencies
        run: |
          cd borgir-app
          npm ci
      - name: Build React App
        run: |
          cd borgir-app
          npm run build
