# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-nodejs
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and
# run tests across different versions of node

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # cache: "npm"

      # Install backend dependencies
      - name: Install Backend Dependencies
        run: |
          cd server
          npm install

      # Install frontend dependencies
      - name: Install Frontend Dependencies
        run: |
          cd borgir-app
          npm install

      # Build the frontend
      - name: Build Frontend
        run: |
          cd borgir-app
          npm run build

      # Run backend tests
      - name: Run Backend Tests
        run: |
          cd server
          npm run test
